# Generated by Django 2.2.2 on 2019-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20190623_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
